---
- name: Common setup for all hosts
  hosts: all
  become: yes
  vars:
    ansible_become_method: doas
  roles:
    - role: common
    - role: authorize_ssh
      # You can override the default path to the public key here, for example:
      # authorized_ssh_key_path: /path/to/your/key.pub

- name: Fstab configuration for s100 hosts
  hosts: s100_hosts
  roles:
    - role: configure_fstab
